jwt:
  config:
    key: hahaha
    ttl: 3600000

org:
  postgresql:
    Driver:

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
  jpa:
   show-sql: true # 默认false，在日志里显示执行的sql语句
   database: postgresql
   hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQL9Dialect

