spring:
  datasource:
    url: jdbc:postgresql://192.168.152.128:5432/postgres
    username: postgres
    password: postgres
    # 初始化大小，最小，最大
    initial-size: 5 
    min-idle: 5
    platform: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: goods-provider
  thymeleaf:
    cache: false

  ###Redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
    password:

    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8002


dubbo:
  application:
    name: goods
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.test.service